import { useLanguage } from "@/components/LanguageProvider";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { ArrowRight, Sparkles, Zap, LayoutTemplate } from "lucide-react";
import { motion } from "framer-motion";
import { useAds } from "@/hooks/use-ads";
import { AdCard } from "@/components/AdCard";

export default function Home() {
  const { t, language } = useLanguage();
  const { data: ads, isLoading } = useAds(language);

  // Background pattern for visual interest
  const bgPattern = `
    radial-gradient(circle at 50% 0%, hsl(var(--primary) / 0.15) 0%, transparent 60%),
    radial-gradient(circle at 100% 0%, hsl(var(--secondary) / 0.1) 0%, transparent 50%)
  `;

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-32">
        <div 
          className="absolute inset-0 z-0 pointer-events-none"
          style={{ background: bgPattern }} 
        />
        
        <div className="container relative z-10 px-4">
          <div className="flex flex-col lg:flex-row items-center gap-12 lg:gap-20">
            <motion.div 
              className="flex-1 text-center lg:text-start"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
                <Sparkles className="w-4 h-4" />
                <span>AI-Powered Advertising</span>
              </div>
              
              <h1 className="text-5xl lg:text-7xl font-extrabold tracking-tight mb-6 leading-[1.1]">
                {t('hero.title')}
              </h1>
              
              <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto lg:mx-0 leading-relaxed">
                {t('hero.subtitle')}
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <Link href="/create">
                  <Button size="lg" className="h-14 px-8 text-lg gap-2 shadow-xl shadow-primary/25 hover:shadow-primary/40 transition-all hover:-translate-y-1">
                    {t('hero.cta')}
                    <ArrowRight className="w-5 h-5 rtl:rotate-180" />
                  </Button>
                </Link>
                <Link href="/ads">
                  <Button size="lg" variant="outline" className="h-14 px-8 text-lg bg-background/50 backdrop-blur hover:bg-background">
                    {t('nav.ads')}
                  </Button>
                </Link>
              </div>
            </motion.div>

            {/* Hero Visual */}
            <motion.div 
              className="flex-1 w-full max-w-xl lg:max-w-none"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8 }}
            >
              <div className="relative aspect-square lg:aspect-[4/3] rounded-3xl overflow-hidden shadow-2xl border border-white/20">
                {/* Abstract marketing visual */}
                <img 
                  src="https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=2574&auto=format&fit=crop" 
                  alt="Creative Workspace" 
                  className="absolute inset-0 w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent flex items-end p-8">
                  <div className="bg-white/10 backdrop-blur-md p-6 rounded-2xl border border-white/20 w-full">
                    <div className="flex items-center gap-4 mb-3">
                      <div className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center text-white font-bold text-lg">
                        SA
                      </div>
                      <div className="text-white">
                        <div className="font-bold">Smart Campaign #1</div>
                        <div className="text-xs opacity-80">Generated by AI • 2 mins ago</div>
                      </div>
                    </div>
                    <div className="h-2 bg-white/20 rounded-full overflow-hidden">
                      <div className="h-full w-3/4 bg-secondary rounded-full" />
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-20 bg-muted/30">
        <div className="container px-4">
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { icon: Sparkles, title: "AI Copywriting", desc: "Generate compelling ad text in seconds using advanced language models." },
              { icon: LayoutTemplate, title: "Smart Layouts", desc: "Beautifully designed templates that adapt to both Arabic and English." },
              { icon: Zap, title: "Instant Publishing", desc: "Create, review, and publish your ads instantly to the marketplace." }
            ].map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="bg-card p-8 rounded-2xl border shadow-sm hover:shadow-md transition-all"
              >
                <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center mb-6">
                  <feature.icon className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
                <p className="text-muted-foreground leading-relaxed">{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Latest Ads */}
      <section className="py-20">
        <div className="container px-4">
          <div className="flex items-center justify-between mb-10">
            <h2 className="text-3xl font-bold">{t('ads.title')}</h2>
            <Link href="/ads">
              <Button variant="ghost" className="gap-2">
                {t('nav.ads')} <ArrowRight className="w-4 h-4 rtl:rotate-180" />
              </Button>
            </Link>
          </div>

          {isLoading ? (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[1, 2, 3].map(i => (
                <div key={i} className="h-80 bg-muted rounded-2xl animate-pulse" />
              ))}
            </div>
          ) : ads && ads.length > 0 ? (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              {ads.slice(0, 3).map((ad, i) => (
                <AdCard key={ad.id} ad={ad} index={i} />
              ))}
            </div>
          ) : (
            <div className="text-center py-20 bg-muted/20 rounded-3xl border border-dashed">
              <h3 className="text-xl font-medium text-muted-foreground">{t('ads.no_ads')}</h3>
            </div>
          )}
        </div>
      </section>
    </div>
  );
}
